"""Parser for Acceptance Criteria generated by the LLM."""

from __future__ import annotations

import logging

from models.acceptance_criteria import (
    AcceptanceCriteria,
)

logger = logging.getLogger(__name__)


class AcceptanceCriteriaParser:
    """Parse LLM output into an AcceptanceCriteria model."""

    @staticmethod
    def parse(
        response: str,
    ) -> AcceptanceCriteria:
        """Parse the Acceptance Criteria response."""

        logger.info(
            "Parsing acceptance criteria."
        )

        criteria: list[str] = []

        blocks = response.split("AC-")

        for block in blocks:

            block = block.strip()

            if not block:
                continue

            lines = block.splitlines()

            criterion = "\n".join(
                line.strip()
                for line in lines[1:]
                if line.strip()
            )

            if criterion:
                criteria.append(criterion)

        logger.info(
            "Acceptance criteria parsed successfully."
        )

        return AcceptanceCriteria(
            criteria=criteria,
        )


__all__ = [
    "AcceptanceCriteriaParser",
]