"""Parse requirement ambiguity assessment into an AmbiguityAssessment model."""

from __future__ import annotations

import logging

from models.ambiguity_assessment import AmbiguityAssessment
from models.enums import AmbiguityLevel
from utils.parser_utils import (
    extract_list,
    extract_score,
    extract_text,
)

logger = logging.getLogger(__name__)


class AmbiguityParser:
    """Parse the LLM ambiguity assessment into an AmbiguityAssessment."""

    @staticmethod
    def parse(response: str) -> AmbiguityAssessment:
        """Parse the ambiguity assessment response.

        Args:
            response:
                LLM response generated by AmbiguityAgent.

        Returns:
            AmbiguityAssessment object.

        Raises:
            RuntimeError:
                If parsing fails.
        """

        logger.info("Parsing ambiguity assessment.")

        try:

            assessment = AmbiguityAssessment(
                ambiguity_score=extract_score(
                    response,
                    "Ambiguity Score",
                ),
                ambiguity_level=AmbiguityLevel(
                    extract_text(
                        response,
                        "Ambiguity Level",
                    )
                ),
                ambiguous_terms=extract_list(
                    response,
                    "Ambiguous Terms",
                    "Missing Information",
                ),
                missing_information=extract_list(
                    response,
                    "Missing Information",
                    "Undefined Business Rules",
                ),
                undefined_business_rules=extract_list(
                    response,
                    "Undefined Business Rules",
                    "Assumptions",
                ),
                assumptions=extract_list(
                    response,
                    "Assumptions",
                    "Conflicting Statements",
                ),
                conflicting_statements=extract_list(
                    response,
                    "Conflicting Statements",
                    "Summary",
                ),
                summary=extract_text(
                    response,
                    "Summary",
                ),
            )

            logger.info(
                "Ambiguity assessment parsed successfully."
            )

            return assessment

        except Exception as exc:

            logger.exception(
                "Failed to parse ambiguity assessment."
            )

            raise RuntimeError(
                "Failed to parse ambiguity assessment."
            ) from exc


__all__ = ["AmbiguityParser"]