"""Parse requirement improvement recommendations into an ImprovementAssessment model."""

from __future__ import annotations

import logging

from models.improvement_assessment import ImprovementAssessment
from utils.parser_utils import (
    extract_list,
    extract_text,
)

logger = logging.getLogger(__name__)


class ImprovementParser:
    """Parse the LLM improvement recommendations."""

    @staticmethod
    def parse(response: str) -> ImprovementAssessment:
        """Parse the improvement recommendation response.

        Args:
            response:
                LLM response generated by ImprovementAgent.

        Returns:
            ImprovementAssessment object.

        Raises:
            RuntimeError:
                If parsing fails.
        """

        logger.info("Parsing improvement recommendations.")

        try:

            assessment = ImprovementAssessment(
                priority_improvements=extract_list(
                    response,
                    "Priority Improvements",
                    "Recommended Requirement Updates",
                ),
                requirement_updates=extract_list(
                    response,
                    "Recommended Requirement Updates",
                    "Expected Impact",
                ),
                expected_impact=extract_list(
                    response,
                    "Expected Impact",
                    "Overall Recommendation",
                ),
                overall_recommendation=extract_text(
                    response,
                    "Overall Recommendation",
                ),
            )

            logger.info(
                "Improvement recommendations parsed successfully."
            )

            return assessment

        except Exception as exc:

            logger.exception(
                "Failed to parse improvement recommendations."
            )

            raise RuntimeError(
                "Failed to parse improvement recommendations."
            ) from exc


__all__ = ["ImprovementParser"]