"""Parse requirement quality assessment into a QualityAssessment model."""

from __future__ import annotations

import logging

from models.enums import RequirementVerdict
from models.quality_assessment import QualityAssessment
from utils.parser_utils import (
    extract_list,
    extract_score,
    extract_text,
)

logger = logging.getLogger(__name__)


class QualityParser:
    """Parse the LLM quality assessment into a QualityAssessment object."""

    @staticmethod
    def parse(response: str) -> QualityAssessment:
        """Parse the quality assessment response.

        Args:
            response: LLM response generated by RequirementQualityAgent.

        Returns:
            QualityAssessment object.

        Raises:
            RuntimeError: If parsing fails unexpectedly.
        """

        logger.info("Parsing quality assessment.")

        try:

            assessment = QualityAssessment(
                overall_score=extract_score(
                    response,
                    "Overall Score",
                ),
                completeness_score=extract_score(
                    response,
                    "Completeness Score",
                ),
                clarity_score=extract_score(
                    response,
                    "Clarity Score",
                ),
                testability_score=extract_score(
                    response,
                    "Testability Score",
                ),
                consistency_score=extract_score(
                    response,
                    "Consistency Score",
                ),
                risk_coverage_score=extract_score(
                    response,
                    "Risk Coverage Score",
                ),
                strengths=extract_list(
                    response,
                    "Strengths",
                    "Weaknesses",
                ),
                weaknesses=extract_list(
                    response,
                    "Weaknesses",
                    "Verdict",
                ),
                verdict=RequirementVerdict(
                    extract_text(
                        response,
                        "Verdict",
                    )
                ),
            )

            logger.info(
                "Quality assessment parsed successfully."
            )

            return assessment

        except Exception as exc:

            logger.exception(
                "Failed to parse quality assessment."
            )

            raise RuntimeError(
                "Failed to parse quality assessment."
            ) from exc


__all__ = ["QualityParser"]