"""Parse requirement risk assessment into a RiskAssessment model."""

from __future__ import annotations

import logging

from models.risk_assessment import RiskAssessment
from utils.parser_utils import (
    extract_list,
    extract_text,
)

logger = logging.getLogger(__name__)


class RiskParser:
    """Parse the LLM risk assessment."""

    @staticmethod
    def parse(response: str) -> RiskAssessment:
        """Parse the risk assessment response.

        Args:
            response:
                LLM response generated by RiskAgent.

        Returns:
            RiskAssessment object.

        Raises:
            RuntimeError:
                If parsing fails.
        """

        logger.info("Parsing risk assessment.")

        try:

            assessment = RiskAssessment(
                high_risks=extract_list(
                    response,
                    "High Risks",
                    "Medium Risks",
                ),
                medium_risks=extract_list(
                    response,
                    "Medium Risks",
                    "Low Risks",
                ),
                low_risks=extract_list(
                    response,
                    "Low Risks",
                    "Testing Focus Areas",
                ),
                testing_focus_areas=extract_list(
                    response,
                    "Testing Focus Areas",
                    "Mitigation Recommendations",
                ),
                mitigation_recommendations=extract_list(
                    response,
                    "Mitigation Recommendations",
                    "Overall Risk Level",
                ),
                overall_risk_level=extract_text(
                    response,
                    "Overall Risk Level",
                ),
            )

            logger.info(
                "Risk assessment parsed successfully."
            )

            return assessment

        except Exception as exc:

            logger.exception(
                "Failed to parse risk assessment."
            )

            raise RuntimeError(
                "Failed to parse risk assessment."
            ) from exc


__all__ = ["RiskParser"]