"""Requirement review agent for QA Copilot."""

from __future__ import annotations

import logging
from typing import Optional

from core.llm_client import LLMClient
from core.prompt_templates import get_requirement_review_prompt

logger = logging.getLogger(__name__)


class RequirementReviewer:
    """Review software requirements through an LLM-based workflow.

    This class is responsible for validating requirement input, building a
    review prompt, sending it to the configured LLM client, and returning the
    generated review text.
    """

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        """Initialize the Requirement Reviewer.

        Args:
            llm_client: Optional preconfigured LLM client. If omitted,
                a new LLMClient instance is created.
        """
        self._llm_client = llm_client or LLMClient()

        logger.info("RequirementReviewer initialized successfully.")

    def review(self, requirement: str) -> str:
        """Review a requirement and return an LLM-generated assessment.

        Args:
            requirement: The requirement text to review.

        Returns:
            A structured requirement review generated by the LLM.

        Raises:
            ValueError: If the requirement is empty or contains only whitespace.
            RuntimeError: If the review generation fails.
        """
        if not isinstance(requirement, str) or not requirement.strip():
            logger.error("Requirement validation failed: input was empty.")
            raise ValueError("Requirement must be a non-empty string.")

        logger.info(
            "Starting requirement review (requirement_length=%d).",
            len(requirement),
        )

        try:
            prompt = get_requirement_review_prompt(requirement)

            logger.info(
                "Requirement review prompt created successfully (prompt_length=%d).",
                len(prompt),
            )

            logger.info("Sending requirement review request to the LLM.")

            review = self._llm_client.generate(prompt)

            logger.info(
                "Requirement review completed successfully (response_length=%d).",
                len(review),
            )

            return review

        except ValueError:
            logger.exception("Requirement validation failed.")
            raise

        except Exception as exc:
            logger.exception(
                "Unexpected error occurred while reviewing the requirement."
            )
            raise RuntimeError(
                "Failed to review requirement."
            ) from exc


__all__ = ["RequirementReviewer"]